### ISSUE TITLE
wiinupro.com website is down

### ISSUE THREAD

**Issue by sanslash332** [KeyPuncher/WiinUPro#124]
As the title says, the old url for the website wiinupro.com is currently unavailable, and redirects to another spam website.

If currently doesn't exist any plans to revive the website, please add description, basic documentation and other simple stuff in the readme.md on this repository, because currently are unavailable any oficial documentation of the tool. So for that, any new user cant found oficial information, wiinupro's news, documentation or something similar.

And well, if the project reached a final state without new updates, please add that information on the readme.md.

Just the old website at google sites is still online, but with outdated information:

https://sites.google.com/site/wiinupro/news?authuser=0

Thanks.

**Comment by KeyPuncher** [comment]
Yep, website is dead and not coming back, this is its home. Also, curious to where people are finding references to wiinupro.com as well as the google drive links.

I've had plans to populate the ReadMe for years now just still haven't got to sit down and dedicate the time to do it. Could probably approach it in small chunks instead of trying to make the whole thing in one go, might actually get done that way.

**Comment by sanslash332** [comment]
Really yes. With a small description of what is wiinupro, where get the latest release and nothing for a begining will be OK.

Other things like changelog, installation guide or other stuf can be populated in the mean time.

**Comment by KeyPuncher** [comment]
Added a Readme and updated the banner on the old site to redirect here.
