### ISSUE TITLE
 WiinUPro does not load controller profiles.

### ISSUE THREAD

**Issue by JoeMamaaas** [KeyPuncher/WiinUPro#127]
This problem is the only one I've had so far. The software crashes every time I try to load a previously saved controller profile. After a (short) inspection of the ".wup" files which showed no apparent anomalies, I decided to reinstall the software, but the problem persists. Since I'm not an English speaker, I'm not sure there's been a similar issue reported before, so I apologize in advance if someone has already reported this issue.

Further information :
My computer is on windows 10.
I haven't tried an older version of WiinUPro than 0.9.7
I'm sending you a .wup file, in case you want to inspect it.
[controller_profile.txt](https://github.com/KeyPuncher/WiinUPro/files/11357329/controller_profile.txt)

I appreciate your work, and I hope you find a solution to the problem.

**Comment by KeyPuncher** [comment]
Give this one a go.
[controller_profile_fixed.txt](https://github.com/KeyPuncher/WiinUPro/files/11711755/controller_profile_fixed.txt)

Issue was that I'm not accounting for unassigned assignments in the config so it runs into a null exception and crashes. Fixed in code, but not built yet. This should provide a workaround.

**Comment by JoeMamaaas** [comment]
I'm glad you found a solution. Thank you so much !
