### ISSUE TITLE
XInput non-functional?

### ISSUE THREAD

**Issue by Paul17041993** [KeyPuncher/WiinUPro#3]
XInput/360 emulation doesn't seem to be functional...

**Comment by pduran5** [comment]
Same problem here with a Switch Pro Controller. When adding an XInput Device, it shows in Control Panel a Controller (XBOX360 For Windows) but it doesn't recognize any button.
Windows 10 Pro x64 Version 1703

**Comment by StrScr** [comment]
@Paul17041993 Can you specify more? Which Windows version are you using? Which controller? Etc.
@pduran5 Does the controller connect successfully to WiinUPro? Did you assign the Xbox controls to the controller? If you answered yes to these, have you tried following the troubleshooting section of the [FAQ](http://www.wiinupro.com/faq)? I may not be able to help much in your case, since I've only connected a Wii U Pro controller.

**Comment by pduran5** [comment]
The Switch Pro Controller connect successfully to WiinUPro and I can see the buttons and the sticks moving when I press them.
Then I add an XInput Device and it appears in Windows Control Panel, but I cannot assign the XInput "virtual" device to the Switch Pro Controller connected device. No matter the order I do (connect controller <-> add device) it doesn't work.
The "Connect as" button is disabled all the time, I don't know if this button is enabled when you add a new XInput device

**Comment by KeyPuncher** [comment]
Connect as is not yet implemented, it's just an idea placeholder that should be done in the future.

It sounds like you haven't added any assignments to the Switch Pro Controller. This doesn't work like WiinUSoft where the assignment is automatic. Since there is not XInput assign button like there is on the Wii U Pro Controller (that was actually meant for testing and left in there on accident) you need to double click or right click a button to assign it.

**Comment by StrScr** [comment]
@pduran5 I suppose the 'Connect As' feature isn't implemented yet. However, you can still press 'Connect', which will add a tab at the top of the program, dedicated to your controller. When you select this tab, you should see a representation of your controller, along with visual feedback of button presses, etc., as you mentioned.
This is the part I'm not too sure of. At least with my Wii U Pro, I get an option, in the form of a button, to map all the controller's features (buttons/sticks/etc.) to an Xbox's. The button says 'Set for Xbox'.
![image](https://user-images.githubusercontent.com/12767988/29287945-33d0260e-80f4-11e7-963a-9ab0a34191a6.png)
If you don't have this button, you should still be able to map each feature to an Xbox's. You can do this by right-clicking each feature and selecting 'Assign'.
![image](https://user-images.githubusercontent.com/12767988/29288046-99b81b7a-80f4-11e7-978a-b3ea74f11214.png)
A window should pop out detailing what you can assign to that feature. You should click the 'Xbox 360' tab to set it to a feature of an Xbox controller. After that, just click the feature you want and select Accept. Repeat this for all other features.
![image](https://user-images.githubusercontent.com/12767988/29288198-1d6dbccc-80f5-11e7-82e9-1aba662d8f60.png)
If, after following these steps, you still have trouble, your Bluetooth settings might be misconfigured or it could be something else. Drop another post here in that case.

**Comment by pduran5** [comment]
Oops, I thought the assignment was automatic. Assigning manually each button works perfectly!!!
Thanks for your help!!

**Comment by Paul17041993** [comment]
turns out you need to grab wiinusoft as well and install the SCP driver from it, it doesn't come with wiinupro and makes no mention of it when you try to add xinput devices without it...

**Comment by StrScr** [comment]
@Paul17041993 Thanks for the tip! I never got affected and I never would've known because I installed it with WiinUSoft.
