### ISSUE TITLE
Wiimote IR sensor down direction not working at all

### ISSUE THREAD

**Issue by LemmusLemmus** [KeyPuncher/WiinUPro#30]
No matter my configurations, the IR sensor won't give any output in the down direction. The "calibration dots" can move in all direction, yet the down direction simply won't give any output in any of the modes (neither "Down" nor any of the "Quick Assign" modes).
Setting the down direction to rumble gives interesting results; it rumbles when moving the wiimote in the up direction.

I'm posting this in the hopes that there is a quick fix to this issue, since it works perfectly in all other directions and in every other way (with the exception of the "Quick assign"->"Mouse"->"Absolute position", where the mouse gets stuck in the lower-left corner, but that's a minor problem in comparison). This problem is the only thing stopping me from emulating both analog sticks.
This error occurs in, as far is I have tested, release version 0.9.4 and 0.9.2.

I have the same problem as can be seen here: https://wiinupro.boards.net/thread/154/problems-mouse-recognition-wiimote-ir

**Comment by Shua-iRL** [comment]
This can be fixed in Line 320 [here](https://github.com/KeyPuncher/WiinUPro/blob/36a2a6dcf9b189b4c537a7ea4aab45bafa87c025/Nintroller/Controllers/Wiimote.cs#L320) in Nintroller > Controllers > Wiimote.cs... 

Line 320 says, `            yield return new KeyValuePair<string, float>(INPUT_NAMES.WIIMOTE.IR_DOWN, irSensor.Y > 0 ? -irSensor.Y : 0);` 

But the ir.Sensor.Y > 0 SHOULD be irSensor.Y < 0      that will fix it.
