### ISSUE TITLE
Controller connected but not responding

### ISSUE THREAD

**Issue by NoxAgilis** [KeyPuncher/WiinUPro#47]
Hi, I don't know the frequency of this problem, but here we go.
A few days ago I received a ripoff wii u pro controller, the same day I found a guide to install this program and use it. The guide told me to install the bluetooth drives, which I found were not necessary later. Whenever tried to connect the controller (via WiinuPro o Soft) it could recognize it, and connect to it, but, at the very moment of the pairing being done, the controller will just shut off, lights will stop blinking and the controller will appear in the program as connect, when trying to identify, either the program will freeze or do nothing
The last thing I tried was to uninstall all the software used, and use the portable version of wiinusoft and reinstall scp and reset the computer, rendering in another failure

**Comment by MoeMonsuta** [comment]
I get this problem all the time. So much I have to reboot to get around it. I use the official pro controller also. It's really finicky.

**Comment by KeyPuncher** [comment]
Imitation and 3rd party variants are not supported. I've never been able to figure out why this would happen. 🤷 
For official controllers the disconnect issue does occasionally happen, though it's still unsure why. Sometimes corrected by pairing with the Wii U. Although I think the culprit for more recent disconnects is due to Windows Updates changing some behind the scenes Bluetooth structure.
