### ISSUE TITLE
Wiimote works, but when nunchuck is connected, only nunchuck works

### ISSUE THREAD

**Issue by bigboibankai** [KeyPuncher/WiinUPro#50]
Basically, I was trying to play rocket league when i realized that when the nunchuck is connected, only the nunchuck inputs are being registered. If i remove the nunchuck, i can use the wiimote, but not with a nunchuck.

**Comment by LemmusLemmus** [comment]
That's odd. With the Nunchuk attached, are the buttons of the Wiimote still assigned to their respective gamepad buttons?
Make sure that the Nunchuk is connected properly, a partial connection can cause issues, although I doubt this is the case.
Also make sure that the device of the assigned buttons on the Nunchuk and the Wiimote are the same, see attached image.
![image](https://user-images.githubusercontent.com/63229554/104012175-a8ea8300-51af-11eb-8a87-6ca52df92734.png)

**To help further troubleshooting:**
Which version of WiinUPro are you using? Would you mind sharing the controller config file (.pref, in the Config folder) and the input profile file (.wup) you are using?

**Comment by KeyPuncher** [comment]
Will re-open if the issue still persists.

**Comment by pnchrx** [comment]
hello I have the same problem they do not work at the same time

**Comment by DiegoJp** [comment]
Hello, this issue is still present. In Wiinusoft, at least.
![imagen](https://user-images.githubusercontent.com/41808318/139486968-46b50c39-7e65-4a16-93f3-5def540290d5.png)
when using this setup (Wiimote + Nunchuk) only inputs from Nunchuk works
as seen as this screenshot:
![imagen](https://user-images.githubusercontent.com/41808318/139487154-d5b364d5-dc2f-48d1-8cd6-2f2e96ad2ad0.png)
(tilting nunchuk to the left and up side + pressing C button. also pressing A+B on Wiimote)

If I unplug the nunchuk, every button works:
![imagen](https://user-images.githubusercontent.com/41808318/139487377-74ccbebd-bef4-4e5a-8016-0ba54573e730.png)
(trying to press every single button while screenshoting, lol)

Please reopen issue!
Thanks in advance, get in touch in you need some testing

**Comment by DiegoJp** [comment]
Nvm, WiinuPro works, Wiinusoft doesn't.

**Comment by Semechko1** [comment]
I have same issue. Nunchuck works wii remote not. Only on wiinusoft. WiinUPro works fine, but WHERE IS MY MOTION??? Only IR sensor? Seriously? What about motion?

**Comment by KeyPuncher** [comment]
> I have same issue. Nunchuck works wii remote not. Only on wiinusoft. WiinUPro works fine, but WHERE IS MY MOTION??? Only IR sensor? Seriously? What about motion?

Please don't mix unrelated topics in existing issues. Also be respectful.

**Comment by KeyPuncher** [comment]
I see what's happening. This is a bug in the current release 3.4.592 on GitHub but at some point I fixed in the repo (3.4.694) and so I just need to create a new release for it.

**Comment by Semechko1** [comment]
Oh sorry, I was just angry then.  Thanks for fixing the bug

**Comment by KeyPuncher** [comment]
I'll create a new release later today, I have plans to attend to at the moment.

**Comment by KeyPuncher** [comment]
Resolved https://github.com/KeyPuncher/WiinUPro/releases/tag/WiinUSoft3.5

**Comment by kepl3r45** [comment]
i had that problem too, i downloaded the 3.5 version and everyting works exept for the pointer, it does not let me asign them either

**Comment by KeyPuncher** [comment]
> i had that problem too, i downloaded the 3.5 version and everyting works exept for the pointer, it does not let me asign them either edit : changing the nunchuk fixed it somehow

Interesting, there are two different types of nunchuks but they shouldn't be being treated any differently. Noted for the future.
