### ISSUE TITLE
Disabled my Bluetooth.

### ISSUE THREAD

**Issue by GoldenAJF** [KeyPuncher/WiinUPro#54]
After I installed this software, my bluetooth no longer works. I have bluetooth via usb so it's not naturally built into my computer, and I can't seem to get it to work.

**Comment by KeyPuncher** [comment]
When you installed it, so that suggests the issue was caused by changes made to the system. The only thing that does that is the SCP drivers required for emulating the 360 controller. Did you unintentionally installed the SCP Bluetooth drivers? That portion of the SCP installer is not needed. There's a little checkbox at the bottom the SCP installer that controls if it is installed or not.

**Comment by KeyPuncher** [comment]
There's also the GCN Adapter driver (via zadig). Did you install that one as well? Because if you're not careful you can end up installing it for the wrong USB device plugged into your computer.

**Comment by GoldenAJF** [comment]
Sorry, I was impatient and abandoned the idea. Sorry for responding later, it completely crossed my mind.

**Comment by KeyPuncher** [comment]
No worries.
