### ISSUE TITLE
Help: How can I "unplug" the input devices when I do not use the app?

### ISSUE THREAD

**Issue by skybird23333** [KeyPuncher/WiinUPro#64]

**Comment by LemmusLemmus** [comment]
If you are talking about the XInput devices, they should automatically be "unplugged" when you shut down WiinUPro or press the "remove" button. If WiinUPro is not shut down properly (for example due to a crash), the XInput devices will remain connected and WiinUPro will not be able to disconnect them. You can manually disconnect these devices by going to "Bluetooth and other devices settings" in Windows 10. Under the header "Other devices" you should find one or several of these: 
![image](https://user-images.githubusercontent.com/63229554/115841197-d71d6700-a41c-11eb-9933-749a70303e7d.png)
Click on them and press "remove device".

If you are talking about the Wii Remotes themselves, simply press the red disconnect button in WiinUPro and hold the power button on the Wii Remote until the controller turns off.

**Comment by skybird23333** [comment]
Hi, thanks for the reply.
No, I am not seeing the device as you said. However, I think this might be an issue with steam as only steam detects this virtual controller and does not recognize it as a Xbox 360 Controller. I will try to connect and disconnect again and see if it removes the device properly.

**Comment by KeyPuncher** [comment]
Steam can sometimes pick up on the HID service created by the Wii/U controller itself. If you need, you may have to remove/unpair the controller from Bluetooth in Windows to get other applications to stop picking it up. It seems like Windows will still list devices as connected even when they're not and you either have to wait or restart to get it to go back to Idle.
