### ISSUE TITLE
Pro controller connected - not recognized as a XI Input

### ISSUE THREAD

**Issue by Alexander-Ninua** [KeyPuncher/WiinUPro#65]
Hello everyone!

Trying to set up the my Wii U pro controller on my new PC. The problem is that I get to connect the Pro controller (it shows the input real time, everything is correct). However, the pc does not see the controller as a "valid gamepad" for gaming. When I press the "Add XI input" button on the main tab, it simply creates an Xbox controller dummy input that is recognized by the game as a controller, but it takes no input from the pro controller. 

Has anybode had the same trouble?

Thank you!

**Comment by LemmusLemmus** [comment]
Hmm. The Add XInput device is suppose to act like a "dummy" device that "fools" the applications you are using. All inputs on your Wii U controller are sent through the XInput device, as such your applications will recognize it as XInput inputs supposedly coming from an Xbox 360 controller. Have you loaded a profile or do you have any inputs assigned to the Wii U Pro controller buttons? WiinUPro will not automatically set up your controller inputs the first time you connect a new controller, you have to tell it to do so.

**Comment by KeyPuncher** [comment]
Reiterating what LemmusLemmus said, typically when users mention this issue it is because they don't realize that unlike WiinUSoft, WiinUPro doesn't automatically assign the button inputs to anything unless configured to do so.

With the first XInput device added, here are some profiles that you can load for your Pro Controller to control the XInput device. Looks like I haven't included the profiles in the setup file.

[XInput Profiles.zip](https://github.com/KeyPuncher/WiinUPro/files/6403112/XInput.Profiles.zip)

**Comment by Alexander-Ninua** [comment]
Thank you very much for your answers! I believe that I have confused WiinUSoft and WiinUPro as well as their uses. I have installed WiinUSoft like I have on my previous pc and everythink works well. Thank you for your good work, I wish you all the best :)
