### ISSUE TITLE
Two xinput for two Wiimotes

### ISSUE THREAD

**Issue by 3sixtyKL** [KeyPuncher/WiinUPro#74]
If I add one Wiimote and add xinput it works perfectly.

I now want to try 2 player, so I add another Wiimote and add another xinput

I can see the 2nd xinput in control panel, but it is assigned to controller 1. How do I make the second xinput "link" to controller 2?

**Comment by LemmusLemmus** [comment]
For each controller input, make sure that the correct Device is selected: 
![image](https://user-images.githubusercontent.com/63229554/133597698-4cb9468a-ba39-48d9-b282-8c2174a2c05e.png)
And don't forget the rumble settings (accessed from the blue "+/- Rumble" button) if you want the controller to rumble from actions in-game for example: 
![image](https://user-images.githubusercontent.com/63229554/133597821-c98850e5-9d9b-4593-9417-58b1e3b4fbaa.png)

To make the connection process quicker next time you decide to use your Wiimotes and WiinUPro, save profiles for Player1 and Player2. You can then either:
A) Load the profiles manually
or
B) Assign, say, your white Wiimote to Player1 and your black Wiimote to Player2
or
C) Set up profile queuing to ensure that the controller connected first will always use the profile Player1, irrespective of which Wiimote that actually was connected.

**Comment by 3sixtyKL** [comment]
Thanks for your reply. I did this though. Actual order:

- Connect two Wiimotes
- Sync in program
- add two xinput devices
- go into each Wiimote and assign keys (one to Device A and one to Device B)
- if i go into any game or program, xinput1 is found and I can configure. Another xinput is available, but the Wiimote2 doesn't work, but if I press Wiimote1 keys it will recognise (seeming like xinput 1 and 2 are both 'assigned' to Wiimote1)

Wiimote 1 and 2 both show as the Player 1 LED, not sure if this makes a difference?

**Comment by LemmusLemmus** [comment]
Well that's definitely odd.

I wonder if this issue is related to XInput at all. If you were to bind one button to a keyboard key for Wiimote A, say the letter 'a', and a different keyboard key for Wiimote B, say the letter 'b', does it work as expected when you try to type?

I'm not sure what causes this problem. The LEDs of the Wiimotes should not both display Player 1, so this leads me to believe that it _may_ be some kind of connection issue (the fault of WiinUPro or Windows). This might be a stretch, but out of curiosity, what exactly is your Wiimote connection process? If I've understood it correctly you first connect the Wiimotes to Windows using the control panel and then connect them to Wiinupro? Would it make any difference whatsoever if you were to merely connect them via WiinUPro's sync button (by simultaneously pressing the sync button under the battery lid on your wiimote), and skip the control panel part altogether?

**Comment by 3sixtyKL** [comment]
Sorry for delay replying, been busy. I tried this way of sync in the
program and not control panel and it works perfectly, thanks!!
